language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script: travis_retry composer install --no-interaction

script:
    - bin/phpunit
